-- MySQL Script generated by MySQL Workbench
-- Qua 07 Fev 2018 09:15:19 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema prog3
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema prog3
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `prog3` DEFAULT CHARACTER SET utf8 ;
USE `prog3` ;

-- -----------------------------------------------------
-- Table `prog3`.`Aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prog3`.`Aluno` (
  `RA` INT UNSIGNED NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(13) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `curso` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`RA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prog3`.`Atividades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prog3`.`Atividades` (
  `Titulo` VARCHAR(45) NOT NULL,
  `CargaHoraria` INT(3) NOT NULL,
  `Ano` DATE NOT NULL,
  `Tipo` VARCHAR(45) NOT NULL,
  `Status` VARCHAR(45) NOT NULL,
  `Aluno_RA` INT UNSIGNED NOT NULL,
  INDEX `fk_Atividades_Aluno1_idx` (`Aluno_RA` ASC),
  CONSTRAINT `fk_Atividades_Aluno1`
    FOREIGN KEY (`Aluno_RA`)
    REFERENCES `prog3`.`Aluno` (`RA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prog3`.`CoordenadorAdministrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prog3`.`CoordenadorAdministrador` (
  `email` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `tipo` TINYINT NOT NULL,
  PRIMARY KEY (`email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prog3`.`Senha`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prog3`.`Senha` (
  `senha` VARCHAR(32) NOT NULL,
  `CoordenadorAdministrador_email` VARCHAR(45) NOT NULL,
  INDEX `fk_Senha_CoordenadorAdministrador_idx` (`CoordenadorAdministrador_email` ASC),
  CONSTRAINT `fk_Senha_CoordenadorAdministrador`
    FOREIGN KEY (`CoordenadorAdministrador_email`)
    REFERENCES `prog3`.`CoordenadorAdministrador` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
