<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>Cadastro Atividades Complementares</title>
    <link rel="stylesheet" href="/home/abilene/IdeaProjects/prog3a/estilo_padrao.css" type="text/css" media="screen">
</head>
<body>

<style>

    form {position: relative;
        top: 0px; right: 0px; bottom: 0px; left: 250px;
        padding: 10px; margin:1em auto;
        background: #fff;box-sizing: border-box;}

    h3 {color: #0000ff; font-size: 22px;text-align: center}
    .campo{width:400px}
    table .dir{font-family: cursive, helvetica; text-align: right; font-size: 18px}
    .botao{width: 205px; height: 35px ; font-size: 18px; color: #0000ff;}

</style>


<h3>Cadastrar Atividade</h3>
<form id="formulario" action="cadastra_atividadades_aluno.php" method="post">
<table>
    <tr> <td class= "dir">Título da Atividade: </td> <td><input class="campo"  type="text" name="titulo" id="titulo"></td></tr>
    <tr> <td class= "dir"> Carga Horária: </td> <td> <input class="campo" type="number" name="cargaHora" id="cargaHora"></td></tr>
    <tr> <td class= "dir"> Ano: </td> <td> <input class="campo" type="date" name="ano" id="ano" ></td></tr>
    <tr><td class="dir"> Tipo: </td> <td><?php
    include('Database.php');
    $db = Database::getInstance();
    $link = $db->getConnection();

    $rs = mysqli_query($link, "SELECT * FROM Tipo_Atividade;");

    echo "<select name='tipo' id='tipo'>";
    while ($reg = mysqli_fetch_object($rs)) {
        echo "<option value='$reg->Atividade'>$reg->Atividade</option>";
    }
    echo "</select>";

            ?></td></tr>
    <tr> <td>  </td> <td><input type="submit" id="enviar"  value="Confirmar" class="botao" name="enviar" id="enviar">
      <input type="button" id="limpar"  value="Limpar" name="limpar" id="limpar" class="botao"></td> </tr>
</table>


    <table>
        <thead>
        <tr>
            <td>Titulo</td>
            <td>Carga Horária</td>
            <td>Ano</td>
            <td>Tipo</td>

        </tr>
        </thead>
        <tbody>
        <?php
        $db = Database::getInstance();
        $link = $db->getConnection();
        session_start();
        $ra = $_SESSION["ra"];

        $results = mysqli_query($link,"SELECT * FROM Atividades WHERE Aluno_RA like '$ra' ORDER BY Ano ASC;");

        //echo $results;
        while($row = mysqli_fetch_array($results)) {
            ?>
            <tr>
                <td><?php echo $row['Titulo']?></td>
                <td><?php echo $row['CargaHoraria']?></td>
                <td><?php echo $row['Ano']?></td>
                <td><?php echo $row['Tipo']?></td>

            </tr>

            <?php
        }
        ?>
        </tbody>
    </table>

<form action="trava_aluno.php" method="post">

    <input type="submit" value="Submeter" class="botao">
</form>



