<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>Lista de Atividades Complementares</title>
    <link rel="stylesheet" href="" type="text/css" media="screen">
</head>
<body>

<style>

    form {position: relative;
        top: 0px; right: 0px; bottom: 0px; left: 250px;
        padding: 10px; margin:1em auto;
        background: #fff;box-sizing: border-box;}

    h3 {color: #0000ff; font-size: 22px;text-align: center}
    .campo{width:400px}
    table .dir{font-family: cursive, helvetica; text-align: right; font-size: 18px}
    .botao{width: 205px; height: 35px ; font-size: 18px; color: #0000ff;}

</style>


<table>
        <thead>
        <tr>
            <td>Titulo</td>
            <td>Carga Horária</td>
            <td>Ano</td>
            <td>Tipo</td>

        </tr>
        </thead>
        <tbody>
        <?php
        $db = Database::getInstance();
        $link = $db->getConnection();
        session_start();
        $ra = $_SESSION["ra"];

        $results = mysqli_query($link,"SELECT * FROM Atividades WHERE Aluno_RA like '$ra'");

        //echo $results;
        while($row = mysqli_fetch_array($results)) {
            ?>
            <tr>
                <td><?php echo $row['Titulo']?></td>
                <td><?php echo $row['CargaHoraria']?></td>
                <td><?php echo $row['Ano']?></td>
                <td><?php echo $row['Tipo']?></td>
                <td><?php echo $row['Status']?></td>

            </tr>

            <?php
        }
        ?>
        </tbody>
    </table>
</body>
</html>