<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Tela Coordenador</title>


    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

</head>
<body>
<style>

</style>
<header>
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <ul class="nav navbar-nav">
                <li><a href="cadastrar_professor.html">Cadastrar Professor</a></li>
                <li class="active"><a href="buscar_aluno.phtml">Buscar Aluno</a></li>
                <li><a href="listar_alunos.phtml">Listar Alunos</a></li>
                <li><a href="designar_professor.phtml">Designar Professor</a></li>
                <li><a href="cadastra_atividades_coordenador.html">Nova Atividade</a></li>
            </ul>
        </div>
    </nav>
</header>

<form id="formulario" name = "f1" method="post" Onsubmit="validarSenha()">
    <table>
        <tr> <td class= "dir">RA: </td> <td><input class="campo"  type="number" name="ra" id="ra" maxlength="12" onkeypress='return SomenteNumero(event)'> </td></tr>
        <tr> <td>  </td> <td><input type="submit" id="enviar"  value="Buscar" class="botao" name="enviar">
    </table>
</form>


<table>
    <thead>
    <tr>
        <td>RA</td>
        <td>Nome</td>
        <td>CPF</td>
        <td>Email</td>
        <td>Curso</td>


    </tr>
    </thead>
    <tbody>


    <?php
   // session_start();
   // $ra = $_SESSION['ra'];


    include "../Database.php";
    $db = Database::getInstance();
    $link = $db->getConnection();

    $ra = mysqli_real_escape_string($link, $_REQUEST['ra']);

    $results = mysqli_query($link,"SELECT * FROM Aluno WHERE RA like $ra;");

    //echo $results;
    while($row = mysqli_fetch_array($results)) {
    ?>
    <tr>
        <td><?php echo $row['RA']?></td>
        <td><?php echo $row['nome']?></td>
        <td><?php echo $row['cpf']?></td>
        <td><?php echo $row['email']?></td>
        <td><?php echo $row['curso']?></td>


    </tr>

    <?php
    }
    ?>
    </tbody>
</table>





</body>
</html>