<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Tela Coordenador</title>


    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

</head>
<body>

<style>

</style>
<header>
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <ul class="nav navbar-nav">
                <li><a href="cadastrar_professor.html">Cadastrar Professor</a></li>
                <li><a href="buscar_aluno.html">Buscar Aluno</a></li>
                <li><a href="listar_alunos.phtml">Listar Alunos</a></li>
                <li class="active"><a href="designar_professor.phtml">Designar Professor</a></li>
                <li><a href="cadastra_atividades_coordenador.html">Nova Atividade</a></li>
            </ul>
        </div>
    </nav>
</header>


<tr><td class="dir"> Email do Professor: </td> <td><?php
        include('../Database.php');
        $db = Database::getInstance();
        $link = $db->getConnection();

        $rs = mysqli_query($link, "SELECT * FROM Professor;");

        echo "<select name='tipo' id='tipo'>";
        while ($reg = mysqli_fetch_object($rs)) {
            echo "<option value='$reg->email'>$reg->email</option>";
        }
        echo "</select>";

        ?></td></tr>

<tr><td class="dir">RA do Aluno: </td> <td><?php

        $rs = mysqli_query($link, "SELECT * FROM Aluno;");

        echo "<select name='tipo' id='tipo'>";
        while ($reg = mysqli_fetch_object($rs)) {
            echo "<option value='$reg->RA'>$reg->RA</option>";
        }
        echo "</select>";

        ?></td></tr>
    
  <form id="formulario" name="formulario" method="get" action="../ambiente_professor/recebe_link_e_avalia.phtml">
  Nome: <input id="RA" name="RA" type="text" value="<php? $RA ?>" />
    <?php $RA = dechex($RA); ?>
    
  <br />
  <input id="btnenviar" name="btnenviar" type="submit" value="Gerar Link" />
 </form>


</body>
</html>
