<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<tr><td class="dir"> Professor: </td> <td><?php
        include('../Database.php');
        $db = Database::getInstance();
        $link = $db->getConnection();

        $rs = mysqli_query($link, "SELECT * FROM Professor;");

        echo "<select name='tipo' id='tipo'>";
        while ($reg = mysqli_fetch_object($rs)) {
            echo "<option value='$reg->nome'>$reg->nome</option>";
        }
        echo "</select>";

        ?></td></tr>

<tr><td class="dir"> Aluno: </td> <td><?php

        $rs = mysqli_query($link, "SELECT * FROM Aluno;");

        echo "<select name='tipo' id='tipo'>";
        while ($reg = mysqli_fetch_object($rs)) {
            echo "<option value='$reg->nome'>$reg->nome</option>";
        }
        echo "</select>";

        ?></td></tr>
</body>
</html>